apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: k8
    trainer: swami
  annotations:
    kubernetes.io/created-by: 'swami'
    jenkins.build.url: 'https://jenkins.cloudswathi.online/expense/job/backend/54'
  spec:
    containers:
    - name: nginx
      image: nginx