kind: Pod
apiVersion: v1
matadata:
  name: env-test
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '20 hours'